### ISSUE TITLE
compile errors with Rust 0.7

### ISSUE THREAD

**Issue by ozten** [servo/rust-http-client#14]
I upgraded to latest Rust (tip of master as well as trying 0.7 snapshot).

I get the following:

```
rust-http-client shout$ make
rustc  http_client.rc -o libhttp_client.dummy
parser.rs:82:12: 82:13 error: type `&[u8]` does not implement any method in scope named `as_imm_buf`
parser.rs:82             }
                         ^
parser.rs:80:36: 80:50 error: the type of this value must be known in this context
parser.rs:80                                     buf as *c_char,
                                                 ^~~~~~~~~~~~~~
error: aborting due to 2 previous errors
make: *** [libhttp_client.dummy] Error 101
```

**Comment by metajack** [comment]
This isn't failing in the servo build. It seems weird. Is there error the same in both version? Servo builds with Rust later than 0.7 release.

**Comment by ozten** [comment]
Yes, same error for both.

I tried to uninstall everything manually and recompile and reinstall. (rm /usr/local/bin/rust\* and rm lib files under /usr/local/lib)

Is there a systematic way to upgrade Rust?

I'll also tried with a fresh clone of this repo.

I'm on Mac 10.7.5. Rust master is `rustc 0.7 (a2db7c1 2013-07-02 09:25:44 -0700)
host: x86_64-apple-darwin`

**Comment by ozten** [comment]
I'm probably doing something dumb. Don't underestimate my abilities in that regard, while troubleshooting :)

**Comment by ozten** [comment]
I didn't have the latest from mozilla-servo/rust-http-client. `rustc 0.8-pre (d582eeb 2013-07-12 21:40:36 -0700)
host: x86_64-apple-darwin` does compile.

0.7 release does not compile. I'll use 0.8-pre.

Thanks!
